version: '2.1.25.{build}'
environment:
  APPVEYOR_TOKEN:
    secure: O4H8KTYEOFxEgsFVxL+Alhj+5LHFzPG8Q8Yi+QpB1yY=
  DOCUMENTATION_TOKEN:
    secure: rJxFNXR0IHBmhibEWD6A2sC5kjerbDfip45s01T7B9YKPrGaQLRhQ67d83GDWARNKjJFMuzIilCEON55uIRyzGg02fPMPI0OVQk

image: Visual Studio 2019
branches:
  only:
  - master
# skip_commits:
#   files:
#   - docs/**/*
pull_requests:
  do_not_increment_build_number: true

install:
  - ps: |
        $key = ("-----BEGIN RSA PRIVATE KEY-----`n" +
                $env:DOCUMENTATION_TOKEN.Replace(' ', "`n") +
                "`n-----END RSA PRIVATE KEY-----`n")
        Set-Content $Home\.ssh\id_rsa $key


before_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            choco install docfx -y
        }

dotnet_csproj:
  patch: true
  file: src\*\*.csproj
  version_prefix: '{version}'
build_script:
  - ps: .\Build.ps1
on_success:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            & docfx content/docfx.json
            if ($lastexitcode -ne 0){
              throw [System.Exception] "docfx build failed with exit code $lastexitcode."
            }

            # git config --global credential.helper store
            # Add-Content "$HOME\.git-credentials" "https://$($env:DOCUMENTATION_TOKEN):x-oauth-basic@github.com`n"
            # git config --global user.email $env:DOCUMENTATION_EMAIL
            # git config --global user.name $env:DOCUMENTATION_USERNAME
            git clone https://github.com/ExtendedXmlSerializer/Documentation.git -b gh-pages .wwwroot -q
            Copy-Item .wwroot/.git content/.wwwroot -recurse
            CD _site
            git add -A 2>&1
            git commit -m "AppVeyor Continuous Deployment Documentation Update v$($env:APPVEYOR_BUILD_VERSION).$($env:APPVEYOR_BUILD_NUMBER)" -q
            git push origin gh-pages -q
        }

nuget:
  project_feed: true
  disable_publish_on_pr: true
artifacts:
- path: src\**\*.nupkg
  name: 'Preview Package {version}'
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: kExW39+W8VRwk3UMReJiT7h2ySKqC9ZpbSPJ87zFNn8uTSLMsZNMCVn/VMrY+7Q7
  on:
    branch: master
    appveyor_repo_tag: true