version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
  - v2.0.0
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/wojtpl2/api/v2/package
  api_key:
    secure: BsmciYCnU/C8uSfDOl1UfCHBEGydgoeDHR0BBqhrdMHGxevM44GP7CsgSt8fUTCx
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: kExW39+W8VRwk3UMReJiT7h2ySKqC9ZpbSPJ87zFNn8uTSLMsZNMCVn/VMrY+7Q7
  on:
    branch: master
    appveyor_repo_tag: true
    
