version: '2.1.25.{build}'
environment:
  APPVEYOR_TOKEN:
    secure: O4H8KTYEOFxEgsFVxL+Alhj+5LHFzPG8Q8Yi+QpB1yY=
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  project_feed: true
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: 'C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtendedXmlSerializer.csproj'
  version_prefix: '{version}'
build_script:
- ps: .\Build.ps1
# test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: kExW39+W8VRwk3UMReJiT7h2ySKqC9ZpbSPJ87zFNn8uTSLMsZNMCVn/VMrY+7Q7
  on:
    branch: master
    appveyor_repo_tag: true